apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jiqt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-jiqt@sha256:e8a179ce88031cf8c4bc53eba68853c53a546f952091d4a72b5977275910c58f
        name: my-nodejs
        resources: {}
status: {}
